### ISSUE TITLE
Это действительно полезно ?

### ISSUE THREAD

**Issue by GulievAnar31** [profpopoff/poleznoe#1]
Привет, Алексей!

Хотелось бы узнать ваше мнение относительно данного репозитория. Есть ли в нем действительно полезные материалы, которые могли бы мне пригодиться? Как вы оцениваете его ценность в контексте моих потребностей? Было бы ли разумно для меня изучить содержимое этого репозитория, и если да, то почему? Буду благодарен за ваше мнение и рекомендации.

**Comment by profpopoff** [comment]
Добрый день, Анан! 

Я так понимаю вопрос о container cherez grid, и думаю, что на все ваши вопросы сможет ответить невероятно интересное и познавательное видео от Kevin Powell (ссылка в приложении №1), с которого я и скопипиздил этот интерфейс. 

Приложение №1: youtube.com/watch?v=c13gpBrnGEw

**Comment by GulievAnar31** [comment]
Спасибо, респект от сприподзинзовского движения
